SELECT * FROM EMP;

--오라클 컨스트레인트스 : Oralce Constraints : 제약조건 
--오라클은 종속된 테이블의 삭제를 방지하고, 테이블에 유효하지 않은 데이터가 입력되는 것을 
--방지하기 위해서 CONSTRAINTS 를 사용한다. 

--USER_CONSTRAINTS : 제약조건을 보기위하 데이터 딕션너리 테이블 
--CONSTRAINT_TYPE
--P : PRIMARY KEY
--R : FOREIGN KEY
--C : CHECK OR NOT NULL
--U : UNIQUE

SELECT CONSTRAINT_NAME, CONSTRAINT_TYPE, TABLE_NAME
FROM   USER_CONSTRAINTS
WHERE  TABLE_NAME = 'CONST_TEST';

CREATE TABLE CONST_TEST(
    CONST_1 NUMBER(4) PRIMARY KEY -- NOT NULL + UNIQUE
   ,CONST_2 VARCHAR2(20) NOT NULL
   ,CONST_3 VARCHAR(10) UNIQUE
);
SELECT * FROM CONST_TEST;
INSERT INTO CONST_TEST VALUES(1111, '1111', '1111');
INSERT INTO CONST_TEST VALUES(1111, '2222', '2222');
INSERT INTO CONST_TEST VALUES(NULL, '2222', '2222');
INSERT INTO CONST_TEST VALUES(1112, NULL, '2222');
INSERT INTO CONST_TEST VALUES(1112, '1112', '1111');
INSERT INTO CONST_TEST VALUES(1112, '1112', '1112');
COMMIT;

SELECT CONSTRAINT_NAME, CONSTRAINT_TYPE, TABLE_NAME, SEARCH_CONDITION
FROM   USER_CONSTRAINTS
WHERE  TABLE_NAME = 'CONST_TEST_1';

CREATE TABLE CONST_TEST_1(
    CONST_1 NUMBER(4) CONSTRAINT CONST_TEST_1_CONT_1_PK PRIMARY KEY 
   ,CONST_2 VARCHAR2(20) CONSTRAINT CONST_TEST_1_CONT_2_NN NOT NULL
   ,CONST_3 VARCHAR(10) CONSTRAINT CONST_TEST_1_CONT_2_UK UNIQUE
);

SELECT CONSTRAINT_NAME, CONSTRAINT_TYPE, TABLE_NAME, SEARCH_CONDITION
FROM   USER_CONSTRAINTS
WHERE  TABLE_NAME = 'CONST_TEST_2';

CREATE TABLE CONST_TEST_2(
    CONST_1 NUMBER(4) 
   ,CONST_2 VARCHAR2(20) CONSTRAINT CONST_TEST_2_CONT_2_NN NOT NULL
   ,CONST_3 VARCHAR(10) 
   ,CONSTRAINT CONST_TEST_2_CONT_1_PK PRIMARY KEY(CONST_1)
   ,CONSTRAINT CONST_TEST_2_CONT_2_UK UNIQUE(CONST_3)
);

-- USER_CONS_COLUMNS : 제약조건이름과 연관된 컬럼을 볼 수 있는 데이터 딕션너리
SELECT * FROM USER_CONS_COLUMNS
WHERE TABLE_NAME = 'EMP';

SELECT * FROM USER_CONS_COLUMNS
WHERE TABLE_NAME = 'DEPT';

DESC DEPT;
SELECT * FROM TAB;

CREATE TABLE EMP06(
    EMPNO NUMBER(4) CONSTRAINT EMP06_EMPNO_PK PRIMARY KEY
   ,ENAME VARCHAR2(10) CONSTRAINT EMP06_ENAME_NN NOT NULL
   ,JOB VARCHAR2(9) CONSTRAINT EMP06_JOB_UK UNIQUE
   ,DEPTNO NUMBER(2) CONSTRAINT EMP06_DEPTNO_FK REFERENCES DEPT(DEPTNO)
);

--CHECK : 저장 가능한 데이터 값의 범위나 조건을 지정하여 설정한 값만을 허용한다. 
--DEFAULT : 정해진 값 입력
CREATE TABLE CON_TEST(
    CON_1 NUMBER(4) PRIMARY KEY 
   ,CON_2 VARCHAR2(2) NOT NULL
   ,GENGER VARCHAR2(1) CHECK(GENDER IN('M', 'F'))
   ,CON_3  VARCHAR2(20) DEFAULT 'KOSMO'
   ,DELETEYN VARCHAR2(1) CHECK(DELETEYN IN('Y', 'N'))
   ,INSERTDATE DEFAULT SYSDATE
   ,UPDATTDATE DEFAULT SYSDATE
);


















