CREATE TABLE SWJ_BOARD(
     BNUM           VARCHAR2(20) PRIMARY KEY
    ,BSUBJECT       VARCHAR2(50) NOT NULL
    ,BWRITER        VARCHAR2(50) NOT NULL
    ,BCONTENTS      VARCHAR2(2000)
    ,BPW            VARCHAR2(20)
    ,DELETEYN       VARCHAR2(1)
    ,INSERTDATE     DATE
    ,UPDATEDATE     DATE
    );

SELECT * FROM SWJ_BOARD;
COMMIT;